# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeebrewer',
            name='id',
        ),
        migrations.AlterField(
            model_name='coffeebrewer',
            name='RFID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
