# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeebrewer',
            name='brews',
            field=models.IntegerField(default=0),
        ),
    ]
