# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_coffeebrewer_brews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoffeeBrewer',
        ),
    ]
