# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.9.5 on 2016-04-29 13:40
=======
# Generated by Django 1.9.5 on 2016-04-29 13:24
>>>>>>> cb9cf1a445250798ce220948fdd4717f4a7b62c4
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0003_delete_coffeebrewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('studmail', models.TextField(default=0, max_length=20, primary_key=True, serialize=False)),
                ('created', models.TextField(default=0, max_length=10)),
            ],
        ),
    ]
