# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='created',
            field=models.IntegerField(default=0),
        ),
    ]
