# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20160501_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='created',
            field=models.BigIntegerField(default=0),
        ),
    ]
