# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20160502_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='studmail',
            field=models.TextField(default=0, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
