# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0002_auto_20160425_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('RFID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.CoffeeBrewer')),
            ],
        ),
    ]
