# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeBrewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('RFID', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('brews', models.IntegerField(default=0)),
            ],
        ),
    ]
