# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0003_remove_coffeebrewer_brews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeebrewer',
            name='RFID',
            field=models.IntegerField(max_length=10),
        ),
    ]
