# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0005_auto_20160428_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='key',
            field=models.IntegerField(default=1),
        ),
    ]
